Add an optional approximation parameter to skip splits in tree search
grf-labs/policytree pull request #5
Opened 2020-03-03 23:28 UTC by erikcs

Adds `split_step`, an optional approximation parameter that controls how many splits to consider.

`split_step` = 1 considers splitting at each distinct value.

`split_step` = 10 considers splitting at every 10'th distinct value.

I did not add the approximation to `level_zero_learning` as that seemed unnecessary

Example:

```R
set.seed(1)
p = 5; n = 40000; prop = 0.2
X = matrix(runif(n*p),n,p)
W = rbinom(n, 1, prop)
tau = 50 * (2 * X[,2] - (1 - X[,1])^4 - 0.5)
mu0 = 50 * (0.5 * (X[,3] - X[,4]))
Y = mu0 + W * tau + runif(n, -80, 80)
IPW.score = cbind((1 - W) / (1 - prop) * Y, W / prop * Y)

# rounding down to ca 100 distinct values
system.time(opt.tree <- policy_tree(round(X, 2), IPW.score, depth = 2))
  user  system elapsed 
 16.365   0.079  16.482 
opt.reward <- mean(IPW.score[cbind(1:n, predict(opt.tree, round(X, 2)))])
opt.reward
[1] 21.90584

system.time(skip.tree <- policy_tree(X, IPW.score, depth = 2, split.step = 100))
   user  system elapsed 
 20.449   0.092  20.860 
skip.reward <- mean(IPW.score[cbind(1:n, predict(skip.tree, round(X, 2)))])
skip.reward
[1] 21.89251
```

2020-03-03 23:51 UTC, erikcs commented
@halflearned split.step = 2 may be of interest in speeding up bandit policy learning

2020-03-05 00:33 UTC, kanodiaayush requested changes

2020-03-05 00:33 UTC, kanodiaayush commented on R/policy_tree.R
> +#'  considers splitting at every 10'th point and may yield a substantial speedup for densely packed
s/may/will

2020-03-05 00:33 UTC, kanodiaayush commented on R/policy_tree.R
> +policy_tree <- function(X, Gamma, depth = 2, split.step = 1) {
why split.step and not split_step?

2020-03-05 00:33 UTC, kanodiaayush commented on src/tree_search.cpp
> +          continue;
split_counter+=1 here

2020-03-05 00:33 UTC, kanodiaayush commented on src/tree_search.cpp
> +        if (++split_counter == split_step) { // only split at every `split_step`th point
s/++split_counter/split_counter

2020-03-05 01:01 UTC, kanodiaayush approved these changes

2020-03-05 01:17 UTC, merged